### ISSUE TITLE
Can't send commands to Flashforge Finder

### ISSUE THREAD

**Issue by Zaureau15** [georgewoodall82/Adv3GUI#1]
Describe the problem you have
Gcode commands not working on Finder (able to connect to printer, but not able to send anything.) Output is blank, and no reaction from printer whatsoever. I couldn't find any instructions on how to format the Gcode to send, so I assumed it's just G00 X1 for example to rapid to X1, but please let me know if this is the wrong format. 

If you know what is causing this and optionally how to fix it, please state that here:

Additional context

**Comment by georgewoodall82** [comment]
G00 isn't a valid gcode command I don't think, G0 should work though

**Comment by georgewoodall82** [comment]
Any update? is the problem resolved?

**Comment by Zaureau15** [comment]
Unfortunately not. Here is a screenshot of the GUI window. It only says connected when I put in the correct IP address, so I know at least something is working right. However, if I send any Gcode, it doesn't actually move on the machine. Is there a specific screen my printer should be on for this to work?

**Comment by georgewoodall82** [comment]
not got the screenshot yet but make sure your printer is on the same network and you have read the troubleshooting guide.
Also, the port for your printer should be 8899, you can find it in settings usually after the colon in the ip
