### ISSUE TITLE
Works with Creator 3 Pro

### ISSUE THREAD

**Issue by AJKnabenbauer** [georgewoodall82/Adv3GUI#2]
Not a problem per-se but the Readme says to open an issue if a printer isn't listed as a tested printer. The script works with the Creator 3 Pro without any modifications. I have yet to test all commands so am not sure if specific ones will have trouble, but most of the standard ones work fine. 

Also wanted to confirm that G28 does work on the Creator 3 Pro.

It may also be worth it to put some of the G-Code commands in the Readme. Since flashforge uses their own proprietary format it is a pain to try and track down info about what commands do what. I attached a pdf with some basic commands that was supplied by Flashforge if you want it. I got it from a google groups conversation. https://groups.google.com/g/flashforge/c/8A7TinFnDMQ

[FlashForge Gcode Protocol(open).pdf](https://github.com/georgewoodall82/Adv3GUI/files/9897409/FlashForge.Gcode.Protocol.open.pdf)

**Comment by georgewoodall82** [comment]
Thanks for the info. I included the gcode documentation pdf in the files and in the README.
